source "https://rubygems.org"

ruby "3.2.3"

gem "sequel", "~> 5.79"
gem "pg", "~> 1.5"
gem "racecar", "~> 2.12"
gem "rdkafka", "~> 0.19"
gem "dotenv", "~> 3.1"
gem "json", "~> 2.7"

group :development, :test do
  gem "rspec", "~> 3.13"
end